name: "Push Docker Container"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Additional tag to push'
        required: false
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: true
        matrix:
          include:
            - ubuntu-version: 20.04
              php-version: 8.1
              node-version: 12
            - ubuntu-version: 20.04
              php-version: 8.2
              node-version: 12
            - ubuntu-version: 22.04
              php-version: 8.2
              node-version: 12
            - ubuntu-version: 22.04
              php-version: 8.3
              node-version: 12
  
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            suffix=-${{matrix.ubuntu-version}}-${{matrix.php-version}}-${{matrix.node-version}}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=${{ inputs.tag }},enable=${{ inputs.tag != '' }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: |
            UBUNTU_VERSION=${{matrix.ubuntu-version}}
            PHP_VERSION=${{matrix.php-version}}
            NODE_VERSION=${{matrix.node-version}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}